//roles
export const LOAD_ROLE_SUCCESS = 'LOAD_ROLE_SUCCESS';
export const CREATE_ROLE = 'CREATE_ROLE';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';

//user
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const CREATE_USER = 'CREATE_USER';
export const CURRENT_USER = 'CURRENT_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

//DOCUMENT 

export const LOAD_DOCUMENT_SUCCESS = 'LOAD_USER_SUCCESS';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
